##
## Makefile for  in /home/moreno_i//afs/renduLocal/projets/irc/tp/cours
## 
## Made by igor morenosemedo
## Login   <moreno_i@epitech.net>
## 
## Started on  Mon Apr 16 17:18:00 2012 igor morenosemedo
## Last update Mon Apr 16 17:20:00 2012 igor morenosemedo
##

NAME	=	tp

all	:
		gcc *.c -W -Wall -Wextra

