##
## Makefile for  in /home/moreno_i//afs/renduLocal/projets/irc/tp/tp_irc
##
## Made by igor morenosemedo
## Login   <moreno_i@epitech.net>
##
## Started on  Mon Apr 16 18:04:57 2012 igor morenosemedo
## Last update Mon Apr 16 18:05:32 2012 igor morenosemedo
##

all:
		gcc *.c -W -Wall -Wextra